### PR TITLE
pick up openstack-helm 6c8041b15f28181fdf7054ea5ff39af48be2ef66

### PR DESCRIPTION
**Pull request by rootfs**
Ceph: Make mon deployment compatible with k8s >= 1.10

Signed-off-by: Huamin Chen <hchen@redhat.com>

### CODE REVIEW

**Comment by pohly** [comment]
The change itself seems to work.

**Comment by dmick** [comment]
@pohly: yes.

**Comment by pohly** [comment]
bfb181967176554ecc0f1ef5685a81d9734a8ea6 still fails for me.

Here's the ceph-mon log:
```
$ kubectl -n ceph logs ceph-mon-gmb6c ceph-mon
+ export LC_ALL=C
+ LC_ALL=C
+ source variables_entrypoint.sh
++ ALL_SCENARIOS='osd osd_directory osd_directory_single osd_ceph_disk osd_ceph_disk_prepare osd_ceph_disk_activate osd_ceph_activate_journal mgr'
++ : ceph
++ : ceph-config/ceph
++ : 192.168.0/20
++ : mon
++ : 0
++ : pohly-desktop
++ : pohly-desktop
++ : /var/lib/ceph/mon/monmap
++ : /var/lib/ceph/mon/ceph-pohly-desktop
++ : 1
++ : 0
++ : mds-pohly-desktop
++ : 0
++ : 100
++ : 0
++ : 0
+++ uuidgen
++ : 8bc144fd-44ba-4c21-83e2-78b880d5b41f
+++ uuidgen
++ : be044ac6-b01c-49a1-a84c-6911db6ac988
++ : root=default host=pohly-desktop
++ : 0
++ : cephfs
++ : cephfs_data
++ : 8
++ : cephfs_metadata
++ : 8
++ : pohly-desktop
++ :
++ :
++ : 8080
++ : 0
++ : 9000
++ : 0.0.0.0
++ : cephnfs
++ : pohly-desktop
++ : 0.0.0.0
++ CLI_OPTS='--cluster ceph'
++ DAEMON_OPTS='--cluster ceph --setuser ceph --setgroup ceph -d'
++ MOUNT_OPTS='-t xfs -o noatime,inode64'
++ MDS_KEYRING=/var/lib/ceph/mds/ceph-mds-pohly-desktop/keyring
++ ADMIN_KEYRING=/etc/ceph/ceph.client.admin.keyring
++ MON_KEYRING=/etc/ceph/ceph.mon.keyring
++ RGW_KEYRING=/var/lib/ceph/radosgw/pohly-desktop/keyring
++ MGR_KEYRING=/var/lib/ceph/mgr/ceph-pohly-desktop/keyring
++ MDS_BOOTSTRAP_KEYRING=/var/lib/ceph/bootstrap-mds/ceph.keyring
++ RGW_BOOTSTRAP_KEYRING=/var/lib/ceph/bootstrap-rgw/ceph.keyring
++ OSD_BOOTSTRAP_KEYRING=/var/lib/ceph/bootstrap-osd/ceph.keyring
++ OSD_PATH_BASE=/var/lib/ceph/osd/ceph
+ source common_functions.sh
++ set -ex
+ [[ -z 192.168.0/20 ]]
+ [[ -z 127.0.0.1 ]]
+ [[ -z 127.0.0.1 ]]
+ [[ -z 192.168.0/20 ]]
+ get_mon_config
++ ceph-conf --lookup fsid -c /etc/ceph/ceph.conf
+ local fsid=eee07bc4-89da-45f7-987d-b1569a065afd
+ timeout=10
+ MONMAP_ADD=
+ [[ -z '' ]]
+ [[ 10 -gt 0 ]]
+ [[ 1 -eq 0 ]]
++ kubectl get pods --namespace=ceph -l application=ceph -l component=mon -o template '--template={{range .items}}{{if .status.podIP}}--add {{.spec.nodeName}} {{.status.podIP}} {{end}} {{end}}'
+ MONMAP_ADD='--add 127.0.0.1 127.0.0.1  '
+ ((  timeout--  ))
+ sleep 1
+ [[ -z --add127.0.0.1127.0.0.1 ]]
+ [[ -z --add127.0.0.1127.0.0.1 ]]
+ '[' -f /var/lib/ceph/mon/monmap ']'
+ monmaptool --print /var/lib/ceph/mon/monmap
+ grep -q 127.0.0.1:6789
+ '[' 0 -eq 0 ']'
+ log '127.0.0.1 already exists in monmap /var/lib/ceph/mon/monmap'
+ '[' -z '127.0.0.1 already exists in monmap /var/lib/ceph/mon/monmap' ']'
++ date '+%F %T'
+ TIMESTAMP='2018-04-23 18:22:42'
+ echo '2018-04-23 18:22:42  /start_mon.sh: 127.0.0.1 already exists in monmap /var/lib/ceph/mon/monmap'
+ return 0
+ return
+ chown ceph. /var/log/ceph
2018-04-23 18:22:42  /start_mon.sh: 127.0.0.1 already exists in monmap /var/lib/ceph/mon/monmap
+ '[' '!' -e /var/lib/ceph/mon/ceph-pohly-desktop/keyring ']'
+ '[' '!' -e /etc/ceph/ceph.mon.keyring ']'
+ touch /etc/ceph/ceph.mon.keyring
+ '[' '!' -e /var/lib/ceph/mon/monmap ']'
+ for keyring in '$OSD_BOOTSTRAP_KEYRING' '$MDS_BOOTSTRAP_KEYRING' '$RGW_BOOTSTRAP_KEYRING' '$ADMIN_KEYRING'
+ ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring
importing contents of /var/lib/ceph/bootstrap-osd/ceph.keyring into /etc/ceph/ceph.mon.keyring
+ for keyring in '$OSD_BOOTSTRAP_KEYRING' '$MDS_BOOTSTRAP_KEYRING' '$RGW_BOOTSTRAP_KEYRING' '$ADMIN_KEYRING'
+ ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /var/lib/ceph/bootstrap-mds/ceph.keyring
importing contents of /var/lib/ceph/bootstrap-mds/ceph.keyring into /etc/ceph/ceph.mon.keyring
+ for keyring in '$OSD_BOOTSTRAP_KEYRING' '$MDS_BOOTSTRAP_KEYRING' '$RGW_BOOTSTRAP_KEYRING' '$ADMIN_KEYRING'
+ ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /var/lib/ceph/bootstrap-rgw/ceph.keyring
importing contents of /var/lib/ceph/bootstrap-rgw/ceph.keyring into /etc/ceph/ceph.mon.keyring
+ for keyring in '$OSD_BOOTSTRAP_KEYRING' '$MDS_BOOTSTRAP_KEYRING' '$RGW_BOOTSTRAP_KEYRING' '$ADMIN_KEYRING'
+ ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /etc/ceph/ceph.client.admin.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /etc/ceph/ceph.mon.keyring
+ ceph-mon --setuser ceph --setgroup ceph --cluster ceph --mkfs -i pohly-desktop --inject-monmap /var/lib/ceph/mon/monmap --keyring /etc/ceph/ceph.mon.keyring --mon-data /var/lib/ceph/mon/ceph-pohly-desktop
2018-04-23 18:22:42.665772 7fc00bcacf00 -1 '/var/lib/ceph/mon/ceph-pohly-desktop' already exists and is not empty: monitor may already exist
+ log SUCCESS
+ '[' -z SUCCESS ']'
++ date '+%F %T'
2018-04-23 18:22:42  /start_mon.sh: SUCCESS
+ TIMESTAMP='2018-04-23 18:22:42'
+ echo '2018-04-23 18:22:42  /start_mon.sh: SUCCESS'
+ return 0
+ exec /usr/bin/ceph-mon --cluster ceph --setuser ceph --setgroup ceph -d -i pohly-desktop --mon-data /var/lib/ceph/mon/ceph-pohly-desktop --public-addr 127.0.0.1:6789
2018-04-23 18:22:42.698267 7f27afc55f00  0 set uid:gid to 64045:64045 (ceph:ceph)
2018-04-23 18:22:42.698286 7f27afc55f00  0 ceph version 12.2.3 (2dab17a455c09584f2a85e6b10888337d1ec8949) luminous (stable), process (unknown), pid 1
2018-04-23 18:22:42.698346 7f27afc55f00  0 pidfile_write: ignore empty --pid-file
2018-04-23 18:22:42.705846 7f27afc55f00  0 load: jerasure load: lrc load: isa 
2018-04-23 18:22:42.705944 7f27afc55f00  0  set rocksdb option compression = kNoCompression
2018-04-23 18:22:42.705958 7f27afc55f00  0  set rocksdb option write_buffer_size = 33554432
2018-04-23 18:22:42.705977 7f27afc55f00  0  set rocksdb option compression = kNoCompression
2018-04-23 18:22:42.705981 7f27afc55f00  0  set rocksdb option write_buffer_size = 33554432
2018-04-23 18:22:42.706121 7f27afc55f00  4 rocksdb: RocksDB version: 5.4.0

2018-04-23 18:22:42.706134 7f27afc55f00  4 rocksdb: Git sha rocksdb_build_git_sha:@0@
2018-04-23 18:22:42.706135 7f27afc55f00  4 rocksdb: Compile date Feb 19 2018
2018-04-23 18:22:42.706137 7f27afc55f00  4 rocksdb: DB SUMMARY

2018-04-23 18:22:42.706211 7f27afc55f00  4 rocksdb: CURRENT file:  CURRENT

2018-04-23 18:22:42.706217 7f27afc55f00  4 rocksdb: IDENTITY file:  IDENTITY

2018-04-23 18:22:42.706221 7f27afc55f00  4 rocksdb: MANIFEST file:  MANIFEST-000167 size: 112 Bytes

2018-04-23 18:22:42.706224 7f27afc55f00  4 rocksdb: SST files in /var/lib/ceph/mon/ceph-pohly-desktop/store.db dir, Total Num: 1, files: 000004.sst 

2018-04-23 18:22:42.706226 7f27afc55f00  4 rocksdb: Write Ahead Log file in /var/lib/ceph/mon/ceph-pohly-desktop/store.db: 000168.log size: 0 ; 

2018-04-23 18:22:42.706227 7f27afc55f00  4 rocksdb:                         Options.error_if_exists: 0
2018-04-23 18:22:42.706229 7f27afc55f00  4 rocksdb:                       Options.create_if_missing: 0
2018-04-23 18:22:42.706229 7f27afc55f00  4 rocksdb:                         Options.paranoid_checks: 1
2018-04-23 18:22:42.706230 7f27afc55f00  4 rocksdb:                                     Options.env: 0x5555bfdc3f20
2018-04-23 18:22:42.706231 7f27afc55f00  4 rocksdb:                                Options.info_log: 0x5555c1e369a0
2018-04-23 18:22:42.706234 7f27afc55f00  4 rocksdb:                          Options.max_open_files: -1
2018-04-23 18:22:42.706235 7f27afc55f00  4 rocksdb:                Options.max_file_opening_threads: 16
2018-04-23 18:22:42.706236 7f27afc55f00  4 rocksdb:                               Options.use_fsync: 0
2018-04-23 18:22:42.706237 7f27afc55f00  4 rocksdb:                       Options.max_log_file_size: 0
2018-04-23 18:22:42.706238 7f27afc55f00  4 rocksdb:                  Options.max_manifest_file_size: 18446744073709551615
2018-04-23 18:22:42.706239 7f27afc55f00  4 rocksdb:                   Options.log_file_time_to_roll: 0
2018-04-23 18:22:42.706239 7f27afc55f00  4 rocksdb:                       Options.keep_log_file_num: 1000
2018-04-23 18:22:42.706240 7f27afc55f00  4 rocksdb:                    Options.recycle_log_file_num: 0
2018-04-23 18:22:42.706241 7f27afc55f00  4 rocksdb:                         Options.allow_fallocate: 1
2018-04-23 18:22:42.706242 7f27afc55f00  4 rocksdb:                        Options.allow_mmap_reads: 0
2018-04-23 18:22:42.706243 7f27afc55f00  4 rocksdb:                       Options.allow_mmap_writes: 0
2018-04-23 18:22:42.706244 7f27afc55f00  4 rocksdb:                        Options.use_direct_reads: 0
2018-04-23 18:22:42.706254 7f27afc55f00  4 rocksdb:                        Options.use_direct_io_for_flush_and_compaction: 0
2018-04-23 18:22:42.706256 7f27afc55f00  4 rocksdb:          Options.create_missing_column_families: 0
2018-04-23 18:22:42.706257 7f27afc55f00  4 rocksdb:                              Options.db_log_dir: 
2018-04-23 18:22:42.706258 7f27afc55f00  4 rocksdb:                                 Options.wal_dir: /var/lib/ceph/mon/ceph-pohly-desktop/store.db
2018-04-23 18:22:42.706258 7f27afc55f00  4 rocksdb:                Options.table_cache_numshardbits: 6
2018-04-23 18:22:42.706259 7f27afc55f00  4 rocksdb:                      Options.max_subcompactions: 1
2018-04-23 18:22:42.706260 7f27afc55f00  4 rocksdb:                  Options.max_background_flushes: 1
2018-04-23 18:22:42.706261 7f27afc55f00  4 rocksdb:                         Options.WAL_ttl_seconds: 0
2018-04-23 18:22:42.706262 7f27afc55f00  4 rocksdb:                       Options.WAL_size_limit_MB: 0
2018-04-23 18:22:42.706262 7f27afc55f00  4 rocksdb:             Options.manifest_preallocation_size: 4194304
2018-04-23 18:22:42.706263 7f27afc55f00  4 rocksdb:                     Options.is_fd_close_on_exec: 1
2018-04-23 18:22:42.706264 7f27afc55f00  4 rocksdb:                   Options.advise_random_on_open: 1
2018-04-23 18:22:42.706265 7f27afc55f00  4 rocksdb:                    Options.db_write_buffer_size: 0
2018-04-23 18:22:42.706266 7f27afc55f00  4 rocksdb:         Options.access_hint_on_compaction_start: 1
2018-04-23 18:22:42.706267 7f27afc55f00  4 rocksdb:  Options.new_table_reader_for_compaction_inputs: 0
2018-04-23 18:22:42.706268 7f27afc55f00  4 rocksdb:               Options.compaction_readahead_size: 0
2018-04-23 18:22:42.706268 7f27afc55f00  4 rocksdb:           Options.random_access_max_buffer_size: 1048576
2018-04-23 18:22:42.706269 7f27afc55f00  4 rocksdb:           Options.writable_file_max_buffer_size: 1048576
2018-04-23 18:22:42.706270 7f27afc55f00  4 rocksdb:                      Options.use_adaptive_mutex: 0
2018-04-23 18:22:42.706271 7f27afc55f00  4 rocksdb:                            Options.rate_limiter: (nil)
2018-04-23 18:22:42.706272 7f27afc55f00  4 rocksdb:     Options.sst_file_manager.rate_bytes_per_sec: 0
2018-04-23 18:22:42.706273 7f27afc55f00  4 rocksdb:                          Options.bytes_per_sync: 0
2018-04-23 18:22:42.706274 7f27afc55f00  4 rocksdb:                      Options.wal_bytes_per_sync: 0
2018-04-23 18:22:42.706274 7f27afc55f00  4 rocksdb:                       Options.wal_recovery_mode: 2
2018-04-23 18:22:42.706275 7f27afc55f00  4 rocksdb:                  Options.enable_thread_tracking: 0
2018-04-23 18:22:42.706276 7f27afc55f00  4 rocksdb:         Options.allow_concurrent_memtable_write: 1
2018-04-23 18:22:42.706277 7f27afc55f00  4 rocksdb:      Options.enable_write_thread_adaptive_yield: 1
2018-04-23 18:22:42.706278 7f27afc55f00  4 rocksdb:             Options.write_thread_max_yield_usec: 100
2018-04-23 18:22:42.706279 7f27afc55f00  4 rocksdb:            Options.write_thread_slow_yield_usec: 3
2018-04-23 18:22:42.706279 7f27afc55f00  4 rocksdb:                               Options.row_cache: None
2018-04-23 18:22:42.706280 7f27afc55f00  4 rocksdb:                              Options.wal_filter: None
2018-04-23 18:22:42.706281 7f27afc55f00  4 rocksdb:             Options.avoid_flush_during_recovery: 0
2018-04-23 18:22:42.706282 7f27afc55f00  4 rocksdb:             Options.base_background_compactions: 1
2018-04-23 18:22:42.706283 7f27afc55f00  4 rocksdb:             Options.max_background_compactions: 1
2018-04-23 18:22:42.706284 7f27afc55f00  4 rocksdb:             Options.avoid_flush_during_shutdown: 0
2018-04-23 18:22:42.706285 7f27afc55f00  4 rocksdb:             Options.delayed_write_rate : 16777216
2018-04-23 18:22:42.706286 7f27afc55f00  4 rocksdb:             Options.max_total_wal_size: 0
2018-04-23 18:22:42.706286 7f27afc55f00  4 rocksdb:             Options.delete_obsolete_files_period_micros: 21600000000
2018-04-23 18:22:42.706287 7f27afc55f00  4 rocksdb:                   Options.stats_dump_period_sec: 600
2018-04-23 18:22:42.706289 7f27afc55f00  4 rocksdb: Compression algorithms supported:
2018-04-23 18:22:42.706290 7f27afc55f00  4 rocksdb: 	Snappy supported: 0
2018-04-23 18:22:42.706290 7f27afc55f00  4 rocksdb: 	Zlib supported: 0
2018-04-23 18:22:42.706291 7f27afc55f00  4 rocksdb: 	Bzip supported: 0
2018-04-23 18:22:42.706292 7f27afc55f00  4 rocksdb: 	LZ4 supported: 0
2018-04-23 18:22:42.706293 7f27afc55f00  4 rocksdb: 	ZSTD supported: 0
2018-04-23 18:22:42.706294 7f27afc55f00  4 rocksdb: Fast CRC32 supported: 0
2018-04-23 18:22:42.706621 7f27afc55f00  4 rocksdb: [/build/ceph-12.2.3/src/rocksdb/db/version_set.cc:2609] Recovering from manifest file: MANIFEST-000167

2018-04-23 18:22:42.706801 7f27afc55f00  4 rocksdb: [/build/ceph-12.2.3/src/rocksdb/db/column_family.cc:407] --------------- Options for column family [default]:

2018-04-23 18:22:42.706813 7f27afc55f00  4 rocksdb:               Options.comparator: leveldb.BytewiseComparator
2018-04-23 18:22:42.706816 7f27afc55f00  4 rocksdb:           Options.merge_operator: 
2018-04-23 18:22:42.706817 7f27afc55f00  4 rocksdb:        Options.compaction_filter: None
2018-04-23 18:22:42.706819 7f27afc55f00  4 rocksdb:        Options.compaction_filter_factory: None
2018-04-23 18:22:42.706820 7f27afc55f00  4 rocksdb:         Options.memtable_factory: SkipListFactory
2018-04-23 18:22:42.706822 7f27afc55f00  4 rocksdb:            Options.table_factory: BlockBasedTable
2018-04-23 18:22:42.706853 7f27afc55f00  4 rocksdb:            table_factory options:   flush_block_policy_factory: FlushBlockBySizePolicyFactory (0x5555c1b160f8)
  cache_index_and_filter_blocks: 1
  cache_index_and_filter_blocks_with_high_priority: 1
  pin_l0_filter_and_index_blocks_in_cache: 1
  index_type: 0
  hash_index_allow_collision: 1
  checksum: 1
  no_block_cache: 0
  block_cache: 0x5555c1e22400
  block_cache_name: LRUCache
  block_cache_options:
    capacity : 134217728
    num_shard_bits : 4
    strict_capacity_limit : 0
    high_pri_pool_ratio: 0.000
  block_cache_compressed: (nil)
  persistent_cache: (nil)
  block_size: 4096
  block_size_deviation: 10
  block_restart_interval: 16
  index_block_restart_interval: 1
  filter_policy: rocksdb.BuiltinBloomFilter
  whole_key_filtering: 1
  format_version: 2

2018-04-23 18:22:42.706910 7f27afc55f00  4 rocksdb:        Options.write_buffer_size: 33554432
2018-04-23 18:22:42.706917 7f27afc55f00  4 rocksdb:  Options.max_write_buffer_number: 2
2018-04-23 18:22:42.706919 7f27afc55f00  4 rocksdb:          Options.compression: NoCompression
2018-04-23 18:22:42.706921 7f27afc55f00  4 rocksdb:                  Options.bottommost_compression: Disabled
2018-04-23 18:22:42.706923 7f27afc55f00  4 rocksdb:       Options.prefix_extractor: nullptr
2018-04-23 18:22:42.706924 7f27afc55f00  4 rocksdb:   Options.memtable_insert_with_hint_prefix_extractor: nullptr
2018-04-23 18:22:42.706926 7f27afc55f00  4 rocksdb:             Options.num_levels: 7
2018-04-23 18:22:42.706927 7f27afc55f00  4 rocksdb:        Options.min_write_buffer_number_to_merge: 1
2018-04-23 18:22:42.706929 7f27afc55f00  4 rocksdb:     Options.max_write_buffer_number_to_maintain: 0
2018-04-23 18:22:42.706930 7f27afc55f00  4 rocksdb:            Options.compression_opts.window_bits: -14
2018-04-23 18:22:42.706931 7f27afc55f00  4 rocksdb:                  Options.compression_opts.level: -1
2018-04-23 18:22:42.706932 7f27afc55f00  4 rocksdb:               Options.compression_opts.strategy: 0
2018-04-23 18:22:42.706934 7f27afc55f00  4 rocksdb:         Options.compression_opts.max_dict_bytes: 0
2018-04-23 18:22:42.706935 7f27afc55f00  4 rocksdb:      Options.level0_file_num_compaction_trigger: 4
2018-04-23 18:22:42.706936 7f27afc55f00  4 rocksdb:          Options.level0_slowdown_writes_trigger: 20
2018-04-23 18:22:42.706941 7f27afc55f00  4 rocksdb:              Options.level0_stop_writes_trigger: 36
2018-04-23 18:22:42.706942 7f27afc55f00  4 rocksdb:                   Options.target_file_size_base: 67108864
2018-04-23 18:22:42.706944 7f27afc55f00  4 rocksdb:             Options.target_file_size_multiplier: 1
2018-04-23 18:22:42.706945 7f27afc55f00  4 rocksdb:                Options.max_bytes_for_level_base: 268435456
2018-04-23 18:22:42.706956 7f27afc55f00  4 rocksdb: Options.level_compaction_dynamic_level_bytes: 0
2018-04-23 18:22:42.706957 7f27afc55f00  4 rocksdb:          Options.max_bytes_for_level_multiplier: 10.000000
2018-04-23 18:22:42.706962 7f27afc55f00  4 rocksdb: Options.max_bytes_for_level_multiplier_addtl[0]: 1
2018-04-23 18:22:42.706964 7f27afc55f00  4 rocksdb: Options.max_bytes_for_level_multiplier_addtl[1]: 1
2018-04-23 18:22:42.706965 7f27afc55f00  4 rocksdb: Options.max_bytes_for_level_multiplier_addtl[2]: 1
2018-04-23 18:22:42.706966 7f27afc55f00  4 rocksdb: Options.max_bytes_for_level_multiplier_addtl[3]: 1
2018-04-23 18:22:42.706967 7f27afc55f00  4 rocksdb: Options.max_bytes_for_level_multiplier_addtl[4]: 1
2018-04-23 18:22:42.706969 7f27afc55f00  4 rocksdb: Options.max_bytes_for_level_multiplier_addtl[5]: 1
2018-04-23 18:22:42.706970 7f27afc55f00  4 rocksdb: Options.max_bytes_for_level_multiplier_addtl[6]: 1
2018-04-23 18:22:42.706971 7f27afc55f00  4 rocksdb:       Options.max_sequential_skip_in_iterations: 8
2018-04-23 18:22:42.706972 7f27afc55f00  4 rocksdb:                    Options.max_compaction_bytes: 1677721600
2018-04-23 18:22:42.706974 7f27afc55f00  4 rocksdb:                        Options.arena_block_size: 4194304
2018-04-23 18:22:42.706975 7f27afc55f00  4 rocksdb:   Options.soft_pending_compaction_bytes_limit: 68719476736
2018-04-23 18:22:42.706976 7f27afc55f00  4 rocksdb:   Options.hard_pending_compaction_bytes_limit: 274877906944
2018-04-23 18:22:42.706977 7f27afc55f00  4 rocksdb:       Options.rate_limit_delay_max_milliseconds: 100
2018-04-23 18:22:42.706979 7f27afc55f00  4 rocksdb:                Options.disable_auto_compactions: 0
2018-04-23 18:22:42.706981 7f27afc55f00  4 rocksdb:                         Options.compaction_style: kCompactionStyleLevel
2018-04-23 18:22:42.706992 7f27afc55f00  4 rocksdb:                           Options.compaction_pri: kByCompensatedSize
2018-04-23 18:22:42.706993 7f27afc55f00  4 rocksdb:  Options.compaction_options_universal.size_ratio: 1
2018-04-23 18:22:42.706995 7f27afc55f00  4 rocksdb: Options.compaction_options_universal.min_merge_width: 2
2018-04-23 18:22:42.706996 7f27afc55f00  4 rocksdb: Options.compaction_options_universal.max_merge_width: 4294967295
2018-04-23 18:22:42.706997 7f27afc55f00  4 rocksdb: Options.compaction_options_universal.max_size_amplification_percent: 200
2018-04-23 18:22:42.706999 7f27afc55f00  4 rocksdb: Options.compaction_options_universal.compression_size_percent: -1
2018-04-23 18:22:42.707001 7f27afc55f00  4 rocksdb: Options.compaction_options_fifo.max_table_files_size: 1073741824
2018-04-23 18:22:42.707002 7f27afc55f00  4 rocksdb:                   Options.table_properties_collectors: 
2018-04-23 18:22:42.707004 7f27afc55f00  4 rocksdb:                   Options.inplace_update_support: 0
2018-04-23 18:22:42.707005 7f27afc55f00  4 rocksdb:                 Options.inplace_update_num_locks: 10000
2018-04-23 18:22:42.707006 7f27afc55f00  4 rocksdb:               Options.memtable_prefix_bloom_size_ratio: 0.000000
2018-04-23 18:22:42.707009 7f27afc55f00  4 rocksdb:   Options.memtable_huge_page_size: 0
2018-04-23 18:22:42.707010 7f27afc55f00  4 rocksdb:                           Options.bloom_locality: 0
2018-04-23 18:22:42.707011 7f27afc55f00  4 rocksdb:                    Options.max_successive_merges: 0
2018-04-23 18:22:42.707013 7f27afc55f00  4 rocksdb:                Options.optimize_filters_for_hits: 0
2018-04-23 18:22:42.707014 7f27afc55f00  4 rocksdb:                Options.paranoid_file_checks: 0
2018-04-23 18:22:42.707015 7f27afc55f00  4 rocksdb:                Options.force_consistency_checks: 0
2018-04-23 18:22:42.707017 7f27afc55f00  4 rocksdb:                Options.report_bg_io_stats: 0
2018-04-23 18:22:42.707824 7f27afc55f00  4 rocksdb: [/build/ceph-12.2.3/src/rocksdb/db/version_set.cc:2859] Recovered from manifest file:/var/lib/ceph/mon/ceph-pohly-desktop/store.db/MANIFEST-000167 succeeded,manifest_file_number is 167, next_file_number is 169, last_sequence is 5, log_number is 0,prev_log_number is 0,max_column_family is 0

2018-04-23 18:22:42.707839 7f27afc55f00  4 rocksdb: [/build/ceph-12.2.3/src/rocksdb/db/version_set.cc:2867] Column family [default] (ID 0), log number is 166

2018-04-23 18:22:42.707909 7f27afc55f00  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1524507762707901, "job": 1, "event": "recovery_started", "log_files": [168]}
2018-04-23 18:22:42.707917 7f27afc55f00  4 rocksdb: [/build/ceph-12.2.3/src/rocksdb/db/db_impl_open.cc:482] Recovering log #168 mode 2
2018-04-23 18:22:42.707993 7f27afc55f00  4 rocksdb: [/build/ceph-12.2.3/src/rocksdb/db/version_set.cc:2395] Creating manifest 170

2018-04-23 18:22:42.709697 7f27afc55f00  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1524507762709691, "job": 1, "event": "recovery_finished"}
2018-04-23 18:22:42.714260 7f27afc55f00  4 rocksdb: [/build/ceph-12.2.3/src/rocksdb/db/db_impl_open.cc:1063] DB pointer 0x5555c1f36000
2018-04-23 18:22:42.714526 7f27afc55f00  0 mon.pohly-desktop does not exist in monmap, will attempt to join an existing cluster
2018-04-23 18:22:42.714908 7f27afc55f00  0 using public_addr 127.0.0.1:6789/0 -> 127.0.0.1:6789/0
2018-04-23 18:22:42.715897 7f27afc55f00  0 starting mon.pohly-desktop rank -1 at public addr 127.0.0.1:6789/0 at bind addr 127.0.0.1:6789/0 mon_data /var/lib/ceph/mon/ceph-pohly-desktop fsid 6ed1f2d9-6538-4a3c-99b0-e2f1face6caa
2018-04-23 18:22:42.716068 7f27afc55f00  0 starting mon.pohly-desktop rank -1 at 127.0.0.1:6789/0 mon_data /var/lib/ceph/mon/ceph-pohly-desktop fsid 6ed1f2d9-6538-4a3c-99b0-e2f1face6caa
2018-04-23 18:22:42.716945 7f27afc55f00  1 mon.pohly-desktop@-1(probing) e0 preinit fsid 6ed1f2d9-6538-4a3c-99b0-e2f1face6caa
2018-04-23 18:22:42.717089 7f27afc55f00  1 mon.pohly-desktop@-1(probing).mds e0 Unable to load 'last_metadata'
2018-04-23 18:22:42.717603 7f27afc55f00 -1 auth: error reading file: /var/lib/ceph/mon/ceph-pohly-desktop/keyring: can't open /var/lib/ceph/mon/ceph-pohly-desktop/keyring: (2) No such file or directory
2018-04-23 18:22:42.717616 7f27afc55f00 -1 mon.pohly-desktop@-1(probing) e0 unable to load initial keyring /etc/ceph/ceph.mon.pohly-desktop.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,
2018-04-23 18:22:42.717621 7f27afc55f00 -1 failed to initialize
```

Is it correct that ceph-authtool is used to create /etc/ceph/ceph.mon.keyring while ceph-mon then looks for /etc/ceph/ceph.mon.pohly-desktop.keyring or /etc/ceph/ceph.keyring?

**Comment by rootfs** [comment]
@pohly can you clean up `/var/lib/ceph/` and try again?

ceph-authtool uses initial `/etc/ceph/ceph.mon.keyring` to import other keyrings.`ceph-mon` uses `/etc/ceph/ceph.mon.keyring` to start.

**Comment by pohly** [comment]
Huamin Chen <notifications@github.com> writes:

> can you clean up `/var/lib/ceph/` and try again?

Clean up where? On the host? I do have such a dir there, but that must
be from my ceph installation on that host.

Everything else runs inside a pristine, clean cluster that I bring up
anew each time I test https://github.com/ceph/ceph-helm/issues/51 - see
that issue for the exact set of commands.

> ceph-authtool uses initial `/etc/ceph/ceph.mon.keyring` to import
> other keyrings.`ceph-mon` uses `/etc/ceph/ceph.mon.keyring` to start.

Hmm, according to the log, ceph-mon does *not* use /etc/ceph/ceph.mon.keyring:

2018-04-23 18:22:42.717616 7f27afc55f00 -1 mon.pohly-desktop@-1(probing) e0 unable to load initial keyring /etc/ceph/ceph.mon.pohly-desktop.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,

**Pull request merged**
