### PR TITLE
add rbac rules for ceph chart

### PR DESCRIPTION
**Pull request by rootfs**
@alram @dmick  PTAL (and test)

### CODE REVIEW

**Comment by alram** [comment]
Just gone one issue creating the storageclass:
``Error: release ceph failed: User "system:serviceaccount:kube-system:default" cannot create storageclasses.storage.k8s.io at the cluster scope. (post storageclasses.storage.k8s.io)``

The rest seems fine.

**Comment by rootfs** [comment]
that's odd, storageclass is set at cluster scope and bound to kube-system:default

**Comment by rootfs** [comment]
@alram fixed, storageclass should be clusterrolebinding, thanks for testing!

**Comment by dmick** [comment]
Man that's a lot of configuration data

**Comment by rootfs** [comment]
write a debug note here so I can remind me when I forget.
- for errors during `helm install`, like seen by @alram . errors are on the console.
- during run time when pod is already created but wants to access resources like endpoint, need to go to the node and see it from `docker logs`. This is for OSD Pod. There is no other sign, too bad.
- could be other errors during `helm del --purge`, need to see tiller logs, i.e. `User "system:serviceaccount:kube-system:default" cannot update daemonsets.extensions in the namespace "ceph"`

**Pull request merged**
